services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: itsjustadev/yuchat:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    command: ["/root/.local/bin/uv", "run", "python", "app/main.py"]
    restart: always
