name: test workflow

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff Format
        run: ruff format .
      - name: Run Ruff Check
        run: ruff check .

  get-info:
    runs-on: ubuntu-latest
    outputs:
      BUILD_URL: ${{ steps.set-vars.outputs.BUILD_URL }}
      BRANCH: ${{ steps.set-vars.outputs.BRANCH }}
      REPO: ${{ steps.set-vars.outputs.REPO }}
      USER: ${{ steps.set-vars.outputs.USER }}
      WORKFLOW_NAME: ${{ steps.set-vars.outputs.WORKFLOW_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: set-vars
        run: |
          echo "BUILD_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "USER=${{ github.actor }}" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=${{ github.workflow }}" >> $GITHUB_ENV

          echo "::set-output name=BUILD_URL::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "::set-output name=BRANCH::${{ github.ref_name }}"
          echo "::set-output name=REPO::${{ github.repository }}"
          echo "::set-output name=USER::${{ github.actor }}"
          echo "::set-output name=WORKFLOW_NAME::${{ github.workflow }}"

  deploy:
    runs-on: ubuntu-latest
    needs: get-info
    steps:
      - name: Deploy job
        run: echo "This is a deploy job. You can add additional logic here"
  
  send-workflow-info:
    runs-on: ubuntu-latest
    needs: [lint, get-info, deploy]
    if: ${{ always() }} 
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Run python script
        env:
          BUILD_URL: ${{ needs.get-info.outputs.BUILD_URL }}
          BRANCH: ${{ needs.get-info.outputs.BRANCH }}
          REPO: ${{ needs.get-info.outputs.REPO }}
          USER: ${{ needs.get-info.outputs.USER }}
          WORKFLOW_NAME: ${{ needs.get-info.outputs.WORKFLOW_NAME }}
          LINT_RESULT: ${{ needs.lint.result }}
          DEPLOY_RESULT: ${{ needs.deploy.result }}
          SEND_INFO_RESULT: ${{ needs.get-info.result }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          source .venv/bin/activate
          python3 new.py
        shell: bash
