name: get pipeline info

on:
  push:
    branches:
      - '**'

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      BUILD_URL: ${{ steps.set-vars.outputs.BUILD_URL }}
      BRANCH: ${{ steps.set-vars.outputs.BRANCH }}
      REPO: ${{ steps.set-vars.outputs.REPO }}
      USER: ${{ steps.set-vars.outputs.USER }}
      WORKFLOW_NAME: ${{ steps.set-vars.outputs.WORKFLOW_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: set-vars
        run: |
          echo "BUILD_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "USER=${{ github.actor }}" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=${{ github.workflow }}" >> $GITHUB_ENV
  
  check-get-info-success:
    runs-on: ubuntu-latest
    needs: get-info
    steps:

      - name: Run python script
        env:
          BUILD_URL: ${{ needs.get-info.outputs.BUILD_URL }}
          BRANCH: ${{ needs.get-info.outputs.BRANCH }}
          REPO: ${{ needs.get-info.outputs.REPO }}
          USER: ${{ needs.get-info.outputs.USER }}
          WORKFLOW_NAME: ${{ needs.get-info.outputs.WORKFLOW_NAME }}
          JOB_RESULT: ${{ needs.get-info.result }}
        run: python3 new.py
