name: Log Build Info

on:
  push:
    branches:
      - '**'

jobs:
  write-info:
    name: Write build info to file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write workflow result to file
        run: |
          echo "info = {" > workflow_result.py
          echo "    'url': 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'," >> workflow_result.py
          echo "    'status': 'in_progress'," >> workflow_result.py
          echo "    'branch': '${{ github.ref_name }}'," >> workflow_result.py
          echo "    'repository': '${{ github.repository }}'," >> workflow_result.py
          echo "    'user': '${{ github.actor }}'," >> workflow_result.py
          echo "    'workflow': '${{ github.workflow }}'" >> workflow_result.py
          echo "}" >> workflow_result.py

      - name: Print file contents
        run: cat workflow_result.py
