name: get pipeline info

on:
  push:
    branches:
      - '**'

jobs:
  get-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set env vars
        run: |
          echo "BUILD_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "USER=${{ github.actor }}" >> $GITHUB_ENV
          echo "WORKFLOW_NAME=${{ github.workflow }}" >> $GITHUB_ENV

      - name: Run python script
        env:
          BUILD_URL: ${{ env.BUILD_URL }}
          BRANCH: ${{ env.BRANCH }}
          REPO: ${{ env.REPO }}
          USER: ${{ env.USER }}
          WORKFLOW_NAME: ${{ env.WORKFLOW_NAME }}
        run: python3 new.py
  
  check-get-info-success:
    runs-on: ubuntu-latest
    needs: get-info
    steps:
      - name: Check previous job status
        run: |
          echo "Get-info job conclusion: ${{ needs.get-info.result }}"
          if [ "${{ needs.get-info.result }}" = "success" ]; then
            echo "get-info job succeeded!"
          else
            echo "get-info job failed or was cancelled!"
            exit 1
          fi
